spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/shipping_db
spring.datasource.username=local
spring.datasource.password=1234567890
spring.jpa.hibernate.ddl-auto=update